baseURL = "https://www.pauloeli.dev/"
title = "paulo.eli"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
enableEmoji = true
dateFormat = "2006-01-02"
enableRobotsTXT = true

[markup.highlight]
style = "github-light"

[params]
author = "Paulo Henrique Eli"
description = "Welcome to my personal website, pauloeli.dev! This project serves as a showcase for my work, blog posts, and contact information."
info = ["Software Architect", "Master’s degree in Information and Communication Technologies"]
keywords = "blog, developer, personal"
avatarURL = "images/avatar.png"
since = 2007
rtl = false
colorScheme = "auto"
hideColorSchemeToggle = false
maxSeeAlsoItems = 5

googleAnalytics = "G-LBWJ4C9C72"

customCSS = []
customSCSS = []
customJS = []
customRemoteJS = []

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/pauloeli/"

[[params.social]]
name = "Gitlab"
icon = "fa fa-2x fa-gitlab"
weight = 2
url = "https://gitlab.com/paulo.eli"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
weight = 4
url = "https://www.linkedin.com/in/pauloeli/"

[languages.en]
languageName = "English"

[[languages.en.menu.main]]
name = "About"
url = "about/"
weight = 1

#[[languages.en.menu.main]]
#name = "Blog"
#weight = 2
#url = "posts/"
#
#[[languages.en.menu.main]]
#name = "Projects"
#weight = 3
#url = "projects/"

[[languages.en.menu.main]]
name = "Contact"
url = "contact/"
weight = 2

[languages.pt-br]
languageName = "Portuguese"

[languages.pt-br.params]
author = "Paulo Henrique Eli"
description = "Bem-vindo ao meu site pessoal, pauloeli.dev! Este projeto serve como uma vitrine para o meu trabalho, blog e informações de contato."
info = ["Arquiteto de Software", "Mestre em Tecnologia da Informação e Comunicação"]
keywords = "blog, desenvolvedor, pessoal"

[[languages.pt-br.menu.main]]
name = "Sobre"
url = "about/"
weight = 1

#[[languages.pt-br.menu.main]]
#name = "Blog"
#weight = 2
#url = "posts/"
#
#[[languages.pt-br.menu.main]]
#name = "Projetos"
#weight = 3
#url = "projects/"

[[languages.pt-br.menu.main]]
name = "Contato"
url = "contact/"
weight = 2

[_build]
list = 'always'
publishResources = true
render = 'always'
